name: 'Dingtalk Webhook'
description: 'Send DingTalk messages via webhook'
inputs:
  webhook:
    description: 'dingtalk webhook'
    required: true

  msgtype:
    description: 'dingtalk message type'
    default: 'text'
  
  content:
    description: 'content for dingtalk message in JSON format'
    required: true

  at:
    description: 'at users in JSON format'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  color: 'blue'
  icon: 'message-square'
