# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test


    - name: send dingtalk message
      uses: ghostoy/dingtalk-action@master
      with:
        webhook: https://oapi.dingtalk.com/robot/send?access_token=8bdab2f4e2ebcfcb59ba7d6a15a7df2b91ca027e0f62c72a451b45277c089576
        secret : SEC008e272d849e43ab3ce932e113992b1d8eea796bc36da4a578461b758c4352c0
        msgtype: markdown
        content: |
          {
             "title": "New push",
             "text": "commit: ${{ github.sha }}"
          }
        at: |
          {
            "atMobiles": [
            "1234567890"
            ],
           "isAtAll": false
          }
